language: node_js
node_js:
  - "8"
  - "10"
  - "11"
services:
  - xvfb
  - docker
cache:
  directories:
    - "node_modules"
git:
  depth: 5
addons:
  firefox: "latest"
before_install:
  - docker pull consul
  - docker run -d --name=dev-consul -e CONSUL_BIND_INTERFACE=eth0 -p 8500:8500 consul
  - npm i -g yarn
install:
  - yarn
  - npm run build:dev
script:
  - npm run lint
  - npm test
after_success: npm run coverage
